api_platform:
    title: Unity-T Zadanie nr 1 i 2
    version: 1.0.0
    formats:
        #        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        json: [ 'application/json' ]
        #
        #        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
#    keep_legacy_inflector: false
    use_symfony_listeners: true
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    patch_formats:
        json: [ 'application/merge-patch+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonld: [ 'application/ld+json' ]      # Hydra error formats
        jsonapi: [ 'application/vnd.api+json' ]